services:
  opengeobot:
    container_name: opengeobot-api
    ports:
      - "8010:8000"
    build:
      context: .
    environment:
      - OPEN_GEOBOT_STORAGE=postgres
      - OPEN_GEOBOT_POSTGRES_DSN=postgresql://opengeo:opengeo_pass@db:5432/opengeobot
    depends_on:
      db:
        condition: service_healthy
    networks:
      - opengeobot-network

  db:
    image: postgres:16-bookworm
    container_name: opengeobot-db
    environment:
      - POSTGRES_USER=opengeo
      - POSTGRES_PASSWORD=opengeo_pass
      - POSTGRES_DB=opengeobot
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opengeo -d opengeobot"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - opengeobot-network

volumes:
  postgres-data:

networks:
  opengeobot-network:
    driver: bridge
