#!/usr/bin/env python3
"""E2E business loop test: QwenPaw planning -> Policy -> Control lease -> Edge dispatch -> Safety -> Execution -> Result.

This test verifies the complete business closed loop defined in
docs/AI开发约束与平台公共能力规范 V1.0.md (lines 61-77):

  User instruction -> IAM -> QwenPaw -> Mission DAG -> Policy -> Fleet ->
  Cloud-edge dispatch -> Edge Safety -> Skill Executor -> Robot ->
  Telemetry -> Trace -> Memory

Prerequisites:
  - Docker Compose stack running with --profile sim (includes qwenpaw,
    agent-runtime, edge-gateway, safety-gateway, local-skill-executor,
    sim-adapter or rosclaw-bridge)
  - Cloud-control running and migrated

Environment variables:
  OPENGEOBOT_BASE_URL   default http://localhost:8080
  OPENGEOBOT_USERNAME   default admin
  OPENGEOBOT_PASSWORD   default admin123
"""

from __future__ import annotations

import json
import os
import sys
import time
import traceback
import urllib.error
import urllib.request

BASE_URL = os.environ.get("OPENGEOBOT_BASE_URL", "http://localhost:8080").rstrip("/")
USERNAME = os.environ.get("OPENGEOBOT_USERNAME", "admin")
PASSWORD = os.environ.get("OPENGEOBOT_PASSWORD", "admin123")
HTTP_TIMEOUT = float(os.environ.get("OPENGEOBOT_HTTP_TIMEOUT", "30"))
POLL_TIMEOUT = float(os.environ.get("OPENGEOBOT_POLL_TIMEOUT", "180"))
MAX_RETRIES = int(os.environ.get("OPENGEOBOT_MAX_RETRIES", "3"))
RETRY_DELAY = float(os.environ.get("OPENGEOBOT_RETRY_DELAY", "2"))
DEFAULT_ROBOT_ID = "rbt_01J00000000000000000000001"


class CheckError(Exception):
    pass


def _request(method: str, path: str, token: str | None = None, body: dict | None = None,
              retries: int = MAX_RETRIES) -> dict:
    """Execute an HTTP request with retry logic for connection errors.

    Controllers return DTOs directly (no ``data`` wrapper).  The global
    Jackson ``SNAKE_CASE`` naming strategy means all JSON field names are
    snake_case.
    """
    url = f"{BASE_URL}{path}"
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    data = json.dumps(body).encode("utf-8") if body else None

    last_exc: Exception | None = None
    for attempt in range(1, retries + 1):
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        try:
            resp = urllib.request.urlopen(req, timeout=HTTP_TIMEOUT)
            raw = resp.read().decode("utf-8")
            return json.loads(raw) if raw else {}
        except urllib.error.HTTPError as exc:
            raw = exc.read().decode("utf-8")
            try:
                err_body = json.loads(raw)
            except (json.JSONDecodeError, ValueError):
                err_body = {"raw": raw}
            # Non-retryable HTTP errors (4xx) - raise immediately
            raise CheckError(f"HTTP {exc.code} on {method} {path}: {err_body}") from exc
        except urllib.error.URLError as exc:
            # Connection errors - retry with backoff
            last_exc = exc
            if attempt < retries:
                print(f"[WARN] Connection error on {method} {path} (attempt {attempt}/{retries}): {exc}")
                time.sleep(RETRY_DELAY * attempt)
            else:
                raise CheckError(
                    f"Connection failed after {retries} attempts on {method} {path}: {exc}"
                ) from exc
    # Should not reach here, but satisfy type checker
    raise CheckError(f"Unexpected state after retries on {method} {path}: {last_exc}")


def login() -> str:
    resp = _request("POST", "/api/v1/auth/login", body={"username": USERNAME, "password": PASSWORD})
    token = resp.get("access_token")
    if not token:
        raise CheckError(f"Login did not return access_token: {resp}")
    print(f"[OK] Logged in as {USERNAME}")
    return token


def ensure_robot_exists(token: str) -> str:
    try:
        resp = _request("GET", f"/api/v1/robots/{DEFAULT_ROBOT_ID}", token=token)
        if resp.get("robot_id"):
            print(f"[OK] Robot {DEFAULT_ROBOT_ID} exists")
            return DEFAULT_ROBOT_ID
    except CheckError:
        pass
    # Create robot if not exists
    try:
        _request("POST", "/api/v1/robots", token=token, body={
            "id": DEFAULT_ROBOT_ID,
            "name": "E2E Test Robot",
            "robot_model_id": "rmdl_01J00000000000000000000001",
            "status": "ONLINE",
        })
        print(f"[OK] Created robot {DEFAULT_ROBOT_ID}")
    except CheckError as exc:
        # Robot might already exist, that's OK
        print(f"[WARN] Robot creation returned: {exc}")
    return DEFAULT_ROBOT_ID


def create_mission(token: str, robot_id: str, objective: str) -> str:
    """Create a mission in PENDING state with a placeholder step.

    ``CreateMissionRequest`` requires ``name`` (@NotBlank), ``robot_id``
    (@NotBlank) and ``steps`` (@NotEmpty).  For the plan-with-agent flow
    we supply a single placeholder step; the real steps are generated by
    QwenPaw via ``/plan-with-agent``.  The natural-language objective is
    passed as ``description``.
    """
    resp = _request("POST", "/api/v1/missions", token=token, body={
        "name": objective,
        "description": objective,
        "robot_id": robot_id,
        "priority": "NORMAL",
        "steps": [
            {
                "skill_id": "placeholder",
                "step_order": 1,
                "input_params": {},
            }
        ],
    })
    mission_id = resp.get("mission_id")
    if not mission_id:
        raise CheckError(f"Mission creation did not return mission_id: {resp}")
    print(f"[OK] Created mission {mission_id} with objective: {objective}")
    return mission_id


def plan_with_agent(token: str, mission_id: str) -> dict:
    print(f"[...] Triggering QwenPaw planning for mission {mission_id}...")
    resp = _request("POST", f"/api/v1/missions/{mission_id}/plan-with-agent", token=token)
    # PlanProposalDto returns: plan_id, mission_id, trace_id, robot_id,
    # steps, confidence, rationale, is_trusted, error, generated_at
    steps = resp.get("steps", [])
    if not steps:
        error = resp.get("error", "unknown")
        raise CheckError(f"QwenPaw planning returned no steps (error={error}): {resp}")
    confidence = resp.get("confidence", "N/A")
    print(f"[OK] QwenPaw generated {len(steps)} plan steps (confidence={confidence})")
    for i, step in enumerate(steps):
        print(f"     Step {i+1}: {step.get('skill_id', 'unknown')} - {step.get('description', '')}")
    return resp


def start_mission(token: str, mission_id: str) -> None:
    _request("POST", f"/api/v1/missions/{mission_id}/start", token=token)
    print(f"[OK] Mission {mission_id} started")


def poll_mission_status(token: str, mission_id: str, timeout: float = POLL_TIMEOUT) -> str:
    start_time = time.time()
    deadline = start_time + timeout
    while time.time() < deadline:
        resp = _request("GET", f"/api/v1/missions/{mission_id}", token=token)
        status = resp.get("status", "UNKNOWN")
        failed_reason = resp.get("failed_reason", "")
        elapsed = int(time.time() - start_time)
        if failed_reason:
            print(f"[...] Mission status: {status} (elapsed {elapsed}s, reason: {failed_reason})")
        else:
            print(f"[...] Mission status: {status} (elapsed {elapsed}s)")
        if status in ("COMPLETED", "FAILED", "CANCELLED"):
            return status
        time.sleep(2)
    raise CheckError(f"Mission {mission_id} did not reach terminal state within {timeout}s")


def verify_trace_exists(token: str, mission_id: str) -> None:
    try:
        resp = _request("GET", "/api/v1/traces", token=token, body=None)
        traces = resp.get("items", [])
        if isinstance(traces, list):
            for trace in traces:
                if mission_id in str(trace):
                    print(f"[OK] Trace found for mission {mission_id}")
                    return
    except CheckError:
        pass
    print(f"[WARN] No trace found for mission {mission_id} (trace API may not be populated yet)")


def verify_safety_events(token: str) -> None:
    try:
        resp = _request("GET", "/api/v1/safety/events", token=token)
        events = resp.get("items", [])
        print(f"[OK] Safety events API accessible ({len(events) if isinstance(events, list) else 'N/A'} events)")
    except CheckError:
        print("[WARN] Safety events API not accessible")


def test_safety_block(token: str, robot_id: str) -> None:
    """Test that the safety gateway blocks overspeed parameters."""
    print("\n=== Test: Safety Gateway Block ===")
    mission_id = create_mission(token, robot_id, "Move forward at 3.0 m/s (overspeed test)")
    try:
        plan_with_agent(token, mission_id)
        # If planning succeeds, try to start and check for safety block
        start_mission(token, mission_id)
        status = poll_mission_status(token, mission_id, timeout=30)
        if status == "FAILED":
            print("[OK] Mission FAILED as expected (safety block or execution error)")
        elif status == "COMPLETED":
            print("[WARN] Mission completed despite overspeed params (safety may not be enforced)")
        else:
            print(f"[INFO] Mission ended with status: {status}")
    except CheckError as exc:
        print(f"[OK] Mission blocked as expected: {exc}")


def main() -> int:
    print("=" * 60)
    print("E2E Business Loop Test")
    print("=" * 60)
    print()

    try:
        # Step 1: Login
        token = login()

        # Step 2: Ensure robot exists
        robot_id = ensure_robot_exists(token)

        # Step 3: Create mission with natural language objective
        print("\n=== Test: Normal Business Loop ===")
        mission_id = create_mission(token, robot_id, "Stand up and move forward 2 meters")

        # Step 4: Trigger QwenPaw planning
        plan_with_agent(token, mission_id)

        # Step 5: Start mission (triggers control lease + edge dispatch)
        start_mission(token, mission_id)

        # Step 6: Poll for completion
        status = poll_mission_status(token, mission_id)
        if status != "COMPLETED":
            raise CheckError(f"Mission did not complete successfully. Final status: {status}")
        print(f"[OK] Mission completed successfully (status={status})")

        # Step 7: Verify trace
        verify_trace_exists(token, mission_id)

        # Step 8: Verify safety events API
        verify_safety_events(token)

        # Step 9: Test safety block scenario
        test_safety_block(token, robot_id)

        print("\n" + "=" * 60)
        print("E2E Business Loop Test: ALL PASSED")
        print("=" * 60)
        return 0

    except CheckError as exc:
        print(f"\n[FAIL] {exc}")
        traceback.print_exc()
        return 1
    except Exception as exc:
        print(f"\n[ERROR] Unexpected error: {exc}")
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
