# Function: AgentRuntimeProvider interface and QwenPawProvider implementation
# Time: 2026-07-06
# Author: AxeXie
"""Agent runtime provider interface and QwenPaw implementation.

The ``AgentRuntimeProvider`` is the single adapter interface through which the
QwenPaw LLM agent runtime is integrated into the platform (per EXT-QWENPAW
contract). The provider converts a mission context into a plan proposal.

**Safety red line**: The agent output is an UNTRUSTED proposal. It must be
validated by Schema, permission, state machine, resource and safety checks
upstream before any skill execution occurs. The provider MUST NOT directly
call ``/cmd_vel``, motors or vendor SDKs — it only produces a plan proposal
that is validated and executed by the downstream pipeline.
"""

from __future__ import annotations

import abc
import json
import re
import uuid
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any

import httpx
import jsonschema
from loguru import logger
from pydantic import BaseModel, Field

from .config import AgentConfig
from .persona import get_persona_content

if TYPE_CHECKING:
    from .nats_client import NatsBridge


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _new_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex}"


# ------------------------------------------------------------------
# Data models.
# ------------------------------------------------------------------


class MissionContext(BaseModel):
    """Input context for mission planning."""

    mission_id: str
    trace_id: str = ""
    robot_id: str = ""
    objective: str = ""
    constraints: dict[str, Any] = Field(default_factory=dict)
    requested_at: str = ""

    model_config = {"extra": "ignore"}


class PlanStep(BaseModel):
    """A single step in a mission plan proposal.

    The ``valid`` and ``validation_error`` fields are populated by the
    provider's schema validation pass.  Invalid steps are retained in the
    proposal (not discarded) so downstream pipelines can inspect them.
    """

    step_id: str
    skill_id: str
    params: dict[str, Any] = Field(default_factory=dict)
    description: str = ""
    valid: bool = True
    validation_error: str | None = None

    model_config = {"extra": "ignore"}


class SkillDefinition(BaseModel):
    """A registered skill definition with its JSON Schema for input params."""

    skill_id: str
    name: str = ""
    input_schema: dict[str, Any] = Field(default_factory=dict)
    description: str = ""

    model_config = {"extra": "ignore"}


class PlanProposal(BaseModel):
    """UNTRUSTED plan proposal generated by the agent runtime.

    The ``is_trusted`` field is always ``False`` - the proposal must be
    validated by Schema, permission, state machine, resource and safety
    checks before any execution occurs.
    """

    plan_id: str
    mission_id: str
    trace_id: str = ""
    robot_id: str = ""
    steps: list[PlanStep] = Field(default_factory=list)
    confidence: float = 0.0
    rationale: str = ""
    is_trusted: bool = False
    error: str | None = None
    generated_at: str

    model_config = {"extra": "ignore"}


class ReplanRequest(BaseModel):
    """Request to replan a mission after a step failure.

    Contains the original objective, completed steps, the failed step and
    remaining steps so the LLM can generate a revised plan with full context.
    """

    mission_id: str
    trace_id: str = ""
    robot_id: str = ""
    original_objective: str = ""
    completed_steps: list[dict[str, Any]] = Field(default_factory=list)
    failed_step: dict[str, Any] = Field(default_factory=dict)
    failure_reason: str = ""
    remaining_steps: list[dict[str, Any]] = Field(default_factory=list)

    model_config = {"extra": "ignore"}


# ------------------------------------------------------------------
# Provider interface.
# ------------------------------------------------------------------


class AgentRuntimeProvider(abc.ABC):
    """Abstract interface for agent runtime providers.

    Per the EXT-QWENPAW contract, QwenPaw is integrated ONLY through this
    interface. Implementations must return UNTRUSTED plan proposals.
    """

    @abc.abstractmethod
    async def generate_plan(self, mission: MissionContext) -> PlanProposal:
        """Generate a mission plan proposal.

        The returned ``PlanProposal`` is UNTRUSTED and must be validated
        upstream before execution.
        """
        ...

    @abc.abstractmethod
    async def continue_plan(self, request: ReplanRequest) -> PlanProposal:
        """Generate a revised plan after a step failure.

        Like ``generate_plan``, the returned ``PlanProposal`` is UNTRUSTED
        and must be validated upstream before execution.
        """
        ...

    async def cancel(self, invocation_id: str) -> None:
        """Cancel an in-flight plan generation.

        Default implementation is a no-op. Stateful providers should
        override this to cancel pending requests.
        """
        return None

    def health(self) -> dict[str, Any]:
        """Return provider health information.

        Default implementation returns ``{"status": "unknown"}``.
        Concrete providers should override to report real status.
        """
        return {"status": "unknown"}


# ------------------------------------------------------------------
# Skill registry – used to validate LLM-generated plan steps.
# ------------------------------------------------------------------


class SkillRegistry(abc.ABC):
    """Abstract interface for looking up registered skill definitions.

    The registry is used by the provider to validate that each ``skill_id``
    in an LLM-generated plan refers to a registered skill and that the step
    ``params`` conform to the skill's ``input_schema``.
    """

    @abc.abstractmethod
    async def get_skill(self, skill_id: str) -> SkillDefinition | None:
        """Return the skill definition for ``skill_id`` or ``None`` if unknown."""
        ...


class StaticSkillRegistry(SkillRegistry):
    """In-memory skill registry backed by a static dictionary.

    Useful for testing and as a fallback when NATS is unavailable.
    """

    def __init__(self, skills: dict[str, SkillDefinition]) -> None:
        self._skills: dict[str, SkillDefinition] = dict(skills)

    async def get_skill(self, skill_id: str) -> SkillDefinition | None:
        return self._skills.get(skill_id)


class NatsSkillRegistry(SkillRegistry):
    """Skill registry that queries the platform via NATS request-reply.

    Skill definitions are cached after the first successful lookup to reduce
    NATS round-trips.  If the NATS request fails (timeout, no responder, etc.)
    the registry returns ``None`` so the provider marks the step as invalid
    rather than discarding the entire proposal.
    """

    def __init__(
        self,
        nats: NatsBridge,
        subject: str = "opengeobot.skill.list",
        timeout: float = 5.0,
    ) -> None:
        self._nats = nats
        self._subject = subject
        self._timeout = timeout
        self._cache: dict[str, SkillDefinition] = {}

    async def get_skill(self, skill_id: str) -> SkillDefinition | None:
        if skill_id in self._cache:
            return self._cache[skill_id]
        try:
            reply = await self._nats.request(
                self._subject,
                json.dumps({"skill_id": skill_id}).encode("utf-8"),
                self._timeout,
            )
            data = json.loads(reply.data)
            # The platform responder returns a JSON array of all published
            # skills. Cache every skill from the response to reduce NATS
            # round-trips for subsequent lookups.
            if isinstance(data, list):
                for item in data:
                    if not isinstance(item, dict):
                        continue
                    skill = SkillDefinition.model_validate(item)
                    self._cache_skill(skill)
                return self._cache.get(skill_id)
            # Backward compat: single-object response
            skill = SkillDefinition.model_validate(data)
            self._cache_skill(skill)
            return self._cache.get(skill_id)
        except Exception as exc:  # noqa: BLE001 - lookup failure marks step invalid
            logger.bind(skill_id=skill_id, error=str(exc)).warning(
                "Skill registry lookup failed"
            )
            return None

    def _cache_skill(self, skill: SkillDefinition) -> None:
        self._cache.setdefault(skill.skill_id, skill)
        if skill.name:
            self._cache.setdefault(skill.name, skill)


# ------------------------------------------------------------------
# QwenPaw provider implementation.
# ------------------------------------------------------------------


class QwenPawProviderError(RuntimeError):
    """Raised when the QwenPaw API call fails."""


class QwenPawProvider(AgentRuntimeProvider):
    """AgentRuntimeProvider implementation that calls the QwenPaw API.

    The provider sends the mission objective to the QwenPaw LLM endpoint and
    parses the response into a ``PlanProposal``. It NEVER calls ``/cmd_vel``,
    motors or vendor SDKs — it only produces an untrusted plan proposal.

    If the QwenPaw API fails or returns an unparseable response, the provider
    returns a ``PlanProposal`` with ``error`` set instead of raising, so the
    downstream pipeline can handle the failure gracefully.
    """

    def __init__(
        self,
        config: AgentConfig,
        skill_registry: SkillRegistry | None = None,
        agent_id: str | None = None,
    ) -> None:
        self._config = config
        self._skill_registry = skill_registry
        self._agent_id: str | None = agent_id
        self._agent_skill_names: list[str] = []

    def set_agent_context(
        self, agent_id: str | None, skill_names: list[str] | None = None
    ) -> None:
        """Set the QwenPaw agent context so it can be included in the prompt.

        When ``agent_id`` is None the provider runs in stateless mode (no
        agent context appended to the system prompt).
        """
        self._agent_id = agent_id
        self._agent_skill_names = list(skill_names) if skill_names else []

    async def generate_plan(self, mission: MissionContext) -> PlanProposal:
        """Call the QwenPaw API and return an UNTRUSTED plan proposal."""
        logger.bind(
            mission_id=mission.mission_id,
            trace_id=mission.trace_id,
            robot_id=mission.robot_id,
        ).info("Generating plan via QwenPaw")

        try:
            response_data = await self._call_qwenpaw_api(mission)
        except QwenPawProviderError as exc:
            logger.bind(
                mission_id=mission.mission_id,
                trace_id=mission.trace_id,
                error=str(exc),
            ).error("QwenPaw API call failed")
            return PlanProposal(
                plan_id=_new_id("plan"),
                mission_id=mission.mission_id,
                trace_id=mission.trace_id,
                robot_id=mission.robot_id,
                is_trusted=False,
                error=str(exc),
                generated_at=_now_iso(),
            )

        proposal = self._parse_response(mission, response_data)
        await self._validate_steps(proposal)
        return proposal

    async def continue_plan(self, request: ReplanRequest) -> PlanProposal:
        """Call the QwenPaw API to replan a failed mission.

        Builds a system prompt that explains the failure context (completed
        steps, the failed step, and remaining steps) and asks the LLM to
        generate a revised plan. The response is parsed the same way as
        ``generate_plan``.
        """
        logger.bind(
            mission_id=request.mission_id,
            trace_id=request.trace_id,
            robot_id=request.robot_id,
        ).info("Replanning mission via QwenPaw after step failure")

        try:
            response_data = await self._call_qwenpaw_replan_api(request)
        except QwenPawProviderError as exc:
            logger.bind(
                mission_id=request.mission_id,
                trace_id=request.trace_id,
                error=str(exc),
            ).error("QwenPaw replan API call failed")
            return PlanProposal(
                plan_id=_new_id("plan"),
                mission_id=request.mission_id,
                trace_id=request.trace_id,
                robot_id=request.robot_id,
                is_trusted=False,
                error=str(exc),
                generated_at=_now_iso(),
            )

        # Reuse _parse_response by wrapping the replan context as a
        # MissionContext (only mission_id/trace_id/robot_id are used).
        mission = MissionContext(
            mission_id=request.mission_id,
            trace_id=request.trace_id,
            robot_id=request.robot_id,
            objective=request.original_objective,
        )
        proposal = self._parse_response(mission, response_data)
        await self._validate_steps(proposal)
        return proposal

    async def cancel(self, invocation_id: str) -> None:
        """No-op for the stateless QwenPaw provider.

        The provider uses per-request HTTP calls with no in-flight state to
        track or cancel. This method exists to satisfy the interface contract.
        """
        return None

    def health(self) -> dict[str, Any]:
        """Return the QwenPaw provider health status."""
        return {
            "status": "healthy",
            "provider": "qwenpaw",
            "endpoint": self._resolve_runtime_endpoint(),
        }

    async def _validate_steps(self, proposal: PlanProposal) -> None:
        """Validate each step's skill_id and params against the skill registry.

        Invalid steps are marked with ``valid=False`` and a ``validation_error``
        but are NOT removed from the proposal.  If no skill registry is
        configured the validation is skipped and all steps remain valid.
        """
        if self._skill_registry is None:
            return

        for step in proposal.steps:
            try:
                skill = await self._skill_registry.get_skill(step.skill_id)
            except Exception as exc:  # noqa: BLE001 - lookup failure marks step invalid
                step.valid = False
                step.validation_error = f"Skill lookup failed: {exc}"
                continue

            if skill is None:
                step.valid = False
                step.validation_error = f"Skill '{step.skill_id}' is not registered"
                continue

            try:
                jsonschema.validate(instance=step.params, schema=skill.input_schema)
            except jsonschema.ValidationError as exc:
                step.valid = False
                step.validation_error = exc.message
            except jsonschema.SchemaError as exc:
                step.valid = False
                step.validation_error = f"Invalid skill schema for '{step.skill_id}': {exc.message}"

    async def _call_qwenpaw_api(self, mission: MissionContext) -> dict[str, Any]:
        """Call the QwenPaw console chat API and return a normalized response."""
        headers: dict[str, str] = {"Content-Type": "application/json"}
        if self._config.qwenpaw_api_key:
            headers["Authorization"] = f"Bearer {self._config.qwenpaw_api_key}"

        skill_defs = await self._fetch_skill_definitions()
        payload = self._build_request_payload(mission, skill_defs)

        try:
            async with httpx.AsyncClient(
                timeout=self._config.qwenpaw_timeout,
            ) as client:
                async with client.stream(
                    "POST",
                    self._resolve_runtime_endpoint(),
                    json=payload,
                    headers=headers,
                ) as response:
                    response.raise_for_status()
                    return await self._read_sse_response(response)
        except httpx.TimeoutException as exc:
            raise QwenPawProviderError(
                f"QwenPaw API timed out after {self._config.qwenpaw_timeout}s"
            ) from exc
        except httpx.HTTPStatusError as exc:
            raise QwenPawProviderError(
                f"QwenPaw API returned HTTP {exc.response.status_code}: "
                f"{exc.response.text[:200]}"
            ) from exc
        except httpx.HTTPError as exc:
            raise QwenPawProviderError(f"QwenPaw API request failed: {exc}") from exc

    async def _fetch_skill_definitions(self) -> list[SkillDefinition]:
        """Best-effort fetch of skill definitions for the system prompt.

        Queries the skill registry for each known skill name.  Failures are
        silently skipped so the prompt falls back to skill names only.
        """
        if not self._skill_registry or not self._agent_skill_names:
            return []
        skills: list[SkillDefinition] = []
        for name in self._agent_skill_names:
            try:
                skill = await self._skill_registry.get_skill(name)
            except Exception:  # noqa: BLE001 - best-effort fetch
                continue
            if skill is not None:
                skills.append(skill)
        return skills

    def _build_system_prompt(
        self, skills: list[SkillDefinition] | None = None
    ) -> str:
        """Build the system prompt, injecting available skill IDs and schemas.

        The base persona (AGENTS.md) defines the "一脑多控" agent role,
        safety red lines and output format. When ``skills`` is provided and
        non-empty, each skill_id and its input_schema are listed. Otherwise
        the agent's configured skill names are used as a fallback.
        """
        prompt = get_persona_content(
            self._config.qwenpaw_persona_dir, "AGENTS.md"
        )

        available: list[tuple[str, str]] = []
        if skills:
            for skill in skills:
                execution_skill_id = skill.name or skill.skill_id
                available.append(
                    (execution_skill_id, json.dumps(skill.input_schema))
                )
        elif self._agent_skill_names:
            for name in self._agent_skill_names:
                available.append((name, "{}"))

        if available:
            prompt += "\n\n可用技能 (Available skills):"
            for i, (skill_id, params) in enumerate(available, 1):
                prompt += f"\n{i}. skill_id: {skill_id}, params: {params}"

        if self._agent_id:
            skills_str = (
                ", ".join(self._agent_skill_names) if self._agent_skill_names else ""
            )
            prompt += (
                f"\n\n你当前作为智能体 '{self._agent_id}' 运行"
                + (f"，绑定技能: {skills_str}。" if skills_str else "。")
            )
        return prompt

    def _build_request_payload(
        self, mission: MissionContext, skills: list[SkillDefinition] | None = None
    ) -> dict[str, Any]:
        """Build the QwenPaw agent-scoped console chat request payload."""
        system_prompt = self._build_system_prompt(skills)
        user_content = json.dumps(
            {
                "mission_id": mission.mission_id,
                "robot_id": mission.robot_id,
                "objective": mission.objective,
                "constraints": mission.constraints,
            },
            ensure_ascii=False,
        )
        prompt = (
            "请基于以下 OpenGeoBot 任务上下文生成任务规划提案。"
            "\n必须严格只输出一个 JSON 对象，不要使用 Markdown 代码块，"
            "不要输出额外解释。"
            "\n\n## 角色与约束\n"
            f"{system_prompt}"
            "\n\n## 任务上下文\n"
            f"{user_content}"
        )
        return {
            "session_id": mission.trace_id or mission.mission_id,
            "user_id": "opengeobot",
            "stream": True,
            "tool_choice": "none",
            "metadata": {
                "mission_id": mission.mission_id,
                "trace_id": mission.trace_id,
                "robot_id": mission.robot_id,
                "request_kind": "plan",
            },
            "input": [
                {
                    "role": "user",
                    "content": [{"type": "text", "text": prompt}],
                }
            ],
        }

    def _build_replan_system_prompt(
        self, request: ReplanRequest, skills: list[SkillDefinition] | None = None
    ) -> str:
        """Build the replan system prompt with failure context.

        Uses the persona (AGENTS.md) as the base so the "一脑多控" role,
        safety red lines and output format stay consistent. Then appends the
        failure context (completed steps, the failed step, remaining steps)
        and asks the LLM to produce a revised plan for the remaining steps.
        """
        prompt = get_persona_content(
            self._config.qwenpaw_persona_dir, "AGENTS.md"
        )
        prompt += (
            "\n\n## 重规划上下文\n\n"
            "你之前规划的任务在执行过程中有步骤失败，请基于以下上下文生成修订后的"
            "规划方案，调整剩余步骤。\n\n"
            f"- 原始目标: {request.original_objective}\n"
            f"- 失败步骤: {json.dumps(request.failed_step, ensure_ascii=False)}\n"
            f"- 失败原因: {request.failure_reason}\n"
        )
        if request.completed_steps:
            prompt += (
                "- 已完成步骤: "
                f"{json.dumps(request.completed_steps, ensure_ascii=False)}\n"
            )
        if request.remaining_steps:
            prompt += (
                "- 失败前剩余步骤: "
                f"{json.dumps(request.remaining_steps, ensure_ascii=False)}\n"
            )

        available: list[tuple[str, str]] = []
        if skills:
            for skill in skills:
                execution_skill_id = skill.name or skill.skill_id
                available.append(
                    (execution_skill_id, json.dumps(skill.input_schema))
                )
        elif self._agent_skill_names:
            for name in self._agent_skill_names:
                available.append((name, "{}"))

        if available:
            prompt += "\n\n可用技能 (Available skills):"
            for i, (skill_id, params) in enumerate(available, 1):
                prompt += f"\n{i}. skill_id: {skill_id}, params: {params}"

        return prompt

    def _build_replan_payload(
        self, request: ReplanRequest, skills: list[SkillDefinition] | None = None
    ) -> dict[str, Any]:
        """Build the QwenPaw agent-scoped console chat replan request payload."""
        system_prompt = self._build_replan_system_prompt(request, skills)
        user_content = json.dumps(
            {
                "mission_id": request.mission_id,
                "robot_id": request.robot_id,
                "original_objective": request.original_objective,
                "failed_step": request.failed_step,
                "failure_reason": request.failure_reason,
                "completed_steps": request.completed_steps,
                "remaining_steps": request.remaining_steps,
            },
            ensure_ascii=False,
        )
        prompt = (
            "请基于以下 OpenGeoBot 失败上下文生成修订后的任务规划提案。"
            "\n必须严格只输出一个 JSON 对象，不要使用 Markdown 代码块，"
            "不要输出额外解释。"
            "\n\n## 角色与约束\n"
            f"{system_prompt}"
            "\n\n## 重规划上下文\n"
            f"{user_content}"
        )
        return {
            "session_id": request.trace_id or request.mission_id,
            "user_id": "opengeobot",
            "stream": True,
            "tool_choice": "none",
            "metadata": {
                "mission_id": request.mission_id,
                "trace_id": request.trace_id,
                "robot_id": request.robot_id,
                "request_kind": "replan",
            },
            "input": [
                {
                    "role": "user",
                    "content": [{"type": "text", "text": prompt}],
                }
            ],
        }

    async def _call_qwenpaw_replan_api(self, request: ReplanRequest) -> dict[str, Any]:
        """Call the QwenPaw console chat API for replanning and normalize it."""
        headers: dict[str, str] = {"Content-Type": "application/json"}
        if self._config.qwenpaw_api_key:
            headers["Authorization"] = f"Bearer {self._config.qwenpaw_api_key}"

        skill_defs = await self._fetch_skill_definitions()
        payload = self._build_replan_payload(request, skill_defs)

        try:
            async with httpx.AsyncClient(
                timeout=self._config.qwenpaw_timeout,
            ) as client:
                async with client.stream(
                    "POST",
                    self._resolve_runtime_endpoint(),
                    json=payload,
                    headers=headers,
                ) as response:
                    response.raise_for_status()
                    return await self._read_sse_response(response)
        except httpx.TimeoutException as exc:
            raise QwenPawProviderError(
                f"QwenPaw replan API timed out after {self._config.qwenpaw_timeout}s"
            ) from exc
        except httpx.HTTPStatusError as exc:
            raise QwenPawProviderError(
                f"QwenPaw replan API returned HTTP {exc.response.status_code}: "
                f"{exc.response.text[:200]}"
            ) from exc
        except httpx.HTTPError as exc:
            raise QwenPawProviderError(f"QwenPaw replan API request failed: {exc}") from exc

    def _resolve_runtime_endpoint(self) -> str:
        """Resolve the effective QwenPaw runtime endpoint for the current agent."""
        endpoint = self._config.qwenpaw_endpoint.strip()
        agent_id = self._agent_id or self._config.qwenpaw_agent_id
        if "{agent_id}" in endpoint:
            return endpoint.format(agent_id=agent_id)
        if endpoint.endswith("/v1/chat/completions"):
            base = endpoint[: -len("/v1/chat/completions")]
            return f"{base}/api/agents/{agent_id}/console/chat"
        return re.sub(
            r"/api/agents/[^/]+/console/chat$",
            f"/api/agents/{agent_id}/console/chat",
            endpoint,
        )

    async def _read_sse_response(
        self, response: httpx.Response
    ) -> dict[str, Any]:
        """Normalize the QwenPaw SSE stream into a chat-completions-like shape."""
        assistant_text = ""
        events: list[dict[str, Any]] = []
        async for raw_line in response.aiter_lines():
            line = raw_line.strip()
            if not line or line.startswith(":") or not line.startswith("data:"):
                continue
            payload = line[5:].strip()
            if not payload or payload == "[DONE]":
                continue
            try:
                event = json.loads(payload)
            except json.JSONDecodeError:
                logger.bind(payload=payload[:200]).debug(
                    "Skipping non-JSON SSE payload from QwenPaw"
                )
                continue
            if not isinstance(event, dict):
                continue
            events.append(event)
            extracted_text = self._extract_assistant_text(event)
            if extracted_text:
                assistant_text = extracted_text

        if not assistant_text:
            raise QwenPawProviderError("QwenPaw SSE stream did not contain assistant content")
        return {
            "choices": [{"message": {"role": "assistant", "content": assistant_text}}],
            "events": events,
        }

    def _extract_assistant_text(self, event: dict[str, Any]) -> str:
        """Extract the most complete assistant text available from one SSE event."""
        role = event.get("role")
        event_type = str(event.get("type", ""))
        if role == "assistant":
            text = self._extract_text_value(event)
            if text:
                return text
        if event_type == "response":
            text = self._extract_text_value(event.get("response"))
            if text:
                return text
        return self._extract_text_value(event.get("output"))

    def _extract_text_value(self, value: Any) -> str:
        """Recursively extract concatenated text fragments from nested payloads."""
        if isinstance(value, str):
            return value.strip()
        if isinstance(value, dict):
            direct_text = value.get("text")
            if isinstance(direct_text, str) and direct_text.strip():
                return direct_text.strip()
            content = value.get("content")
            if isinstance(content, list):
                text = self._extract_text_value(content)
                if text:
                    return text
            output = value.get("output")
            if isinstance(output, list):
                text = self._extract_text_value(output)
                if text:
                    return text
            parts: list[str] = []
            for item in value.values():
                text = self._extract_text_value(item)
                if text:
                    parts.append(text)
            return "\n".join(parts).strip()
        if isinstance(value, list):
            parts = [self._extract_text_value(item) for item in value]
            return "\n".join(part for part in parts if part).strip()
        return ""

    def _parse_response(
        self, mission: MissionContext, response_data: dict[str, Any]
    ) -> PlanProposal:
        """Parse the QwenPaw API response into a PlanProposal."""
        plan_id = _new_id("plan")
        now = _now_iso()

        # The response is expected to be a chat-completions response with
        # choices[0].message.content containing the plan JSON.
        try:
            choices = response_data.get("choices", [])
            if not choices:
                return PlanProposal(
                    plan_id=plan_id,
                    mission_id=mission.mission_id,
                    trace_id=mission.trace_id,
                    robot_id=mission.robot_id,
                    is_trusted=False,
                    error="QwenPaw returned no choices",
                    generated_at=now,
                )

            content = self._extract_json_content(
                choices[0].get("message", {}).get("content", "")
            )
            plan_data = json.loads(content) if isinstance(content, str) else content
            if not isinstance(plan_data, dict):
                return PlanProposal(
                    plan_id=plan_id,
                    mission_id=mission.mission_id,
                    trace_id=mission.trace_id,
                    robot_id=mission.robot_id,
                    is_trusted=False,
                    error="QwenPaw response content is not a JSON object",
                    generated_at=now,
                )

            raw_steps = plan_data.get("steps", [])
            steps: list[PlanStep] = []
            for i, raw_step in enumerate(raw_steps):
                if not isinstance(raw_step, dict):
                    continue
                steps.append(
                    PlanStep(
                        step_id=f"{plan_id}_step_{i}",
                        skill_id=str(raw_step.get("skill_id", "")),
                        params=raw_step.get("params", {}) if isinstance(
                            raw_step.get("params"), dict
                        ) else {},
                        description=str(raw_step.get("description", "")),
                    )
                )

            confidence = float(plan_data.get("confidence", 0.0))
            # Clamp confidence to [0.0, 1.0].
            confidence = max(0.0, min(1.0, confidence))

            return PlanProposal(
                plan_id=plan_id,
                mission_id=mission.mission_id,
                trace_id=mission.trace_id,
                robot_id=mission.robot_id,
                steps=steps,
                confidence=confidence,
                rationale=str(plan_data.get("rationale", "")),
                is_trusted=False,
                generated_at=now,
            )
        except (json.JSONDecodeError, TypeError, ValueError) as exc:
            return PlanProposal(
                plan_id=plan_id,
                mission_id=mission.mission_id,
                trace_id=mission.trace_id,
                robot_id=mission.robot_id,
                is_trusted=False,
                error=f"Failed to parse QwenPaw response: {exc}",
                generated_at=now,
            )

    def _extract_json_content(self, content: Any) -> Any:
        """Extract a JSON payload from mixed assistant prose plus JSON."""
        if not isinstance(content, str):
            return content
        normalized = content.strip()
        normalized = re.sub(r'^```(?:json)?\s*\n?', '', normalized).rstrip("`").rstrip()
        if normalized.startswith("{") or normalized.startswith("["):
            return normalized

        json_fragment = self._find_first_json_object(normalized)
        return json_fragment if json_fragment is not None else normalized

    def _find_first_json_object(self, text: str) -> str | None:
        """Return the first balanced JSON object embedded in free-form text."""
        start = text.find("{")
        if start < 0:
            return None

        depth = 0
        in_string = False
        escaped = False
        for index in range(start, len(text)):
            char = text[index]
            if in_string:
                if escaped:
                    escaped = False
                elif char == "\\":
                    escaped = True
                elif char == '"':
                    in_string = False
                continue

            if char == '"':
                in_string = True
            elif char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth == 0:
                    return text[start : index + 1]
        return None
