# Function: AgentRuntimeProvider interface and QwenPawProvider implementation
# Time: 2026-07-06
# Author: AxeXie
"""Agent runtime provider interface and QwenPaw implementation.

The ``AgentRuntimeProvider`` is the single adapter interface through which the
QwenPaw LLM agent runtime is integrated into the platform (per EXT-QWENPAW
contract). The provider converts a mission context into a plan proposal.

**Safety red line**: The agent output is an UNTRUSTED proposal. It must be
validated by Schema, permission, state machine, resource and safety checks
upstream before any skill execution occurs. The provider MUST NOT directly
call ``/cmd_vel``, motors or vendor SDKs — it only produces a plan proposal
that is validated and executed by the downstream pipeline.
"""

from __future__ import annotations

import abc
import json
import uuid
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any

import httpx
import jsonschema
from loguru import logger
from pydantic import BaseModel, Field

from .config import AgentConfig

if TYPE_CHECKING:
    from .nats_client import NatsBridge


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _new_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex}"


# ------------------------------------------------------------------
# Data models.
# ------------------------------------------------------------------


class MissionContext(BaseModel):
    """Input context for mission planning."""

    mission_id: str
    trace_id: str = ""
    robot_id: str = ""
    objective: str = ""
    constraints: dict[str, Any] = Field(default_factory=dict)
    requested_at: str = ""

    model_config = {"extra": "ignore"}


class PlanStep(BaseModel):
    """A single step in a mission plan proposal.

    The ``valid`` and ``validation_error`` fields are populated by the
    provider's schema validation pass.  Invalid steps are retained in the
    proposal (not discarded) so downstream pipelines can inspect them.
    """

    step_id: str
    skill_id: str
    params: dict[str, Any] = Field(default_factory=dict)
    description: str = ""
    valid: bool = True
    validation_error: str | None = None

    model_config = {"extra": "ignore"}


class SkillDefinition(BaseModel):
    """A registered skill definition with its JSON Schema for input params."""

    skill_id: str
    input_schema: dict[str, Any] = Field(default_factory=dict)

    model_config = {"extra": "ignore"}


class PlanProposal(BaseModel):
    """UNTRUSTED plan proposal generated by the agent runtime.

    The ``is_trusted`` field is always ``False`` — the proposal must be
    validated by Schema, permission, state machine, resource and safety
    checks before any execution occurs.
    """

    plan_id: str
    mission_id: str
    trace_id: str = ""
    robot_id: str = ""
    steps: list[PlanStep] = Field(default_factory=list)
    confidence: float = 0.0
    rationale: str = ""
    is_trusted: bool = False
    error: str | None = None
    generated_at: str

    model_config = {"extra": "ignore"}


# ------------------------------------------------------------------
# Provider interface.
# ------------------------------------------------------------------


class AgentRuntimeProvider(abc.ABC):
    """Abstract interface for agent runtime providers.

    Per the EXT-QWENPAW contract, QwenPaw is integrated ONLY through this
    interface. Implementations must return UNTRUSTED plan proposals.
    """

    @abc.abstractmethod
    async def generate_plan(self, mission: MissionContext) -> PlanProposal:
        """Generate a mission plan proposal.

        The returned ``PlanProposal`` is UNTRUSTED and must be validated
        upstream before execution.
        """
        ...


# ------------------------------------------------------------------
# Skill registry – used to validate LLM-generated plan steps.
# ------------------------------------------------------------------


class SkillRegistry(abc.ABC):
    """Abstract interface for looking up registered skill definitions.

    The registry is used by the provider to validate that each ``skill_id``
    in an LLM-generated plan refers to a registered skill and that the step
    ``params`` conform to the skill's ``input_schema``.
    """

    @abc.abstractmethod
    async def get_skill(self, skill_id: str) -> SkillDefinition | None:
        """Return the skill definition for ``skill_id`` or ``None`` if unknown."""
        ...


class StaticSkillRegistry(SkillRegistry):
    """In-memory skill registry backed by a static dictionary.

    Useful for testing and as a fallback when NATS is unavailable.
    """

    def __init__(self, skills: dict[str, SkillDefinition]) -> None:
        self._skills: dict[str, SkillDefinition] = dict(skills)

    async def get_skill(self, skill_id: str) -> SkillDefinition | None:
        return self._skills.get(skill_id)


class NatsSkillRegistry(SkillRegistry):
    """Skill registry that queries the platform via NATS request-reply.

    Skill definitions are cached after the first successful lookup to reduce
    NATS round-trips.  If the NATS request fails (timeout, no responder, etc.)
    the registry returns ``None`` so the provider marks the step as invalid
    rather than discarding the entire proposal.
    """

    def __init__(
        self,
        nats: NatsBridge,
        subject: str = "opengeobot.skill.list",
        timeout: float = 5.0,
    ) -> None:
        self._nats = nats
        self._subject = subject
        self._timeout = timeout
        self._cache: dict[str, SkillDefinition] = {}

    async def get_skill(self, skill_id: str) -> SkillDefinition | None:
        if skill_id in self._cache:
            return self._cache[skill_id]
        try:
            reply = await self._nats.request(
                self._subject,
                json.dumps({"skill_id": skill_id}).encode("utf-8"),
                self._timeout,
            )
            data = json.loads(reply.data)
            skill = SkillDefinition.model_validate(data)
            self._cache[skill_id] = skill
            return skill
        except Exception as exc:  # noqa: BLE001 - lookup failure marks step invalid
            logger.bind(skill_id=skill_id, error=str(exc)).warning(
                "Skill registry lookup failed"
            )
            return None


# ------------------------------------------------------------------
# QwenPaw provider implementation.
# ------------------------------------------------------------------


class QwenPawProviderError(RuntimeError):
    """Raised when the QwenPaw API call fails."""


class QwenPawProvider(AgentRuntimeProvider):
    """AgentRuntimeProvider implementation that calls the QwenPaw API.

    The provider sends the mission objective to the QwenPaw LLM endpoint and
    parses the response into a ``PlanProposal``. It NEVER calls ``/cmd_vel``,
    motors or vendor SDKs — it only produces an untrusted plan proposal.

    If the QwenPaw API fails or returns an unparseable response, the provider
    returns a ``PlanProposal`` with ``error`` set instead of raising, so the
    downstream pipeline can handle the failure gracefully.
    """

    def __init__(
        self,
        config: AgentConfig,
        skill_registry: SkillRegistry | None = None,
        agent_id: str | None = None,
    ) -> None:
        self._config = config
        self._skill_registry = skill_registry
        self._agent_id: str | None = agent_id
        self._agent_skill_names: list[str] = []

    def set_agent_context(
        self, agent_id: str | None, skill_names: list[str] | None = None
    ) -> None:
        """Set the QwenPaw agent context so it can be included in the prompt.

        When ``agent_id`` is None the provider runs in stateless mode (no
        agent context appended to the system prompt).
        """
        self._agent_id = agent_id
        self._agent_skill_names = list(skill_names) if skill_names else []

    async def generate_plan(self, mission: MissionContext) -> PlanProposal:
        """Call the QwenPaw API and return an UNTRUSTED plan proposal."""
        logger.bind(
            mission_id=mission.mission_id,
            trace_id=mission.trace_id,
            robot_id=mission.robot_id,
        ).info("Generating plan via QwenPaw")

        try:
            response_data = await self._call_qwenpaw_api(mission)
        except QwenPawProviderError as exc:
            logger.bind(
                mission_id=mission.mission_id,
                trace_id=mission.trace_id,
                error=str(exc),
            ).error("QwenPaw API call failed")
            return PlanProposal(
                plan_id=_new_id("plan"),
                mission_id=mission.mission_id,
                trace_id=mission.trace_id,
                robot_id=mission.robot_id,
                is_trusted=False,
                error=str(exc),
                generated_at=_now_iso(),
            )

        proposal = self._parse_response(mission, response_data)
        await self._validate_steps(proposal)
        return proposal

    async def _validate_steps(self, proposal: PlanProposal) -> None:
        """Validate each step's skill_id and params against the skill registry.

        Invalid steps are marked with ``valid=False`` and a ``validation_error``
        but are NOT removed from the proposal.  If no skill registry is
        configured the validation is skipped and all steps remain valid.
        """
        if self._skill_registry is None:
            return

        for step in proposal.steps:
            try:
                skill = await self._skill_registry.get_skill(step.skill_id)
            except Exception as exc:  # noqa: BLE001 - lookup failure marks step invalid
                step.valid = False
                step.validation_error = f"Skill lookup failed: {exc}"
                continue

            if skill is None:
                step.valid = False
                step.validation_error = f"Skill '{step.skill_id}' is not registered"
                continue

            try:
                jsonschema.validate(instance=step.params, schema=skill.input_schema)
            except jsonschema.ValidationError as exc:
                step.valid = False
                step.validation_error = exc.message
            except jsonschema.SchemaError as exc:
                step.valid = False
                step.validation_error = f"Invalid skill schema for '{step.skill_id}': {exc.message}"

    async def _call_qwenpaw_api(self, mission: MissionContext) -> dict[str, Any]:
        """Call the QwenPaw HTTP API and return the parsed response body."""
        headers: dict[str, str] = {"Content-Type": "application/json"}
        if self._config.qwenpaw_api_key:
            headers["Authorization"] = f"Bearer {self._config.qwenpaw_api_key}"

        payload = self._build_request_payload(mission)

        try:
            async with httpx.AsyncClient(
                timeout=self._config.qwenpaw_timeout,
            ) as client:
                response = await client.post(
                    self._config.qwenpaw_endpoint,
                    json=payload,
                    headers=headers,
                )
                response.raise_for_status()
                return response.json()
        except httpx.TimeoutException as exc:
            raise QwenPawProviderError(
                f"QwenPaw API timed out after {self._config.qwenpaw_timeout}s"
            ) from exc
        except httpx.HTTPStatusError as exc:
            raise QwenPawProviderError(
                f"QwenPaw API returned HTTP {exc.response.status_code}: "
                f"{exc.response.text[:200]}"
            ) from exc
        except httpx.HTTPError as exc:
            raise QwenPawProviderError(f"QwenPaw API request failed: {exc}") from exc

    def _build_request_payload(self, mission: MissionContext) -> dict[str, Any]:
        """Build the QwenPaw chat-completions request payload."""
        system_prompt = (
            "You are a mission planning assistant for a robot platform. "
            "Given a mission objective, produce a plan as a JSON object with "
            '"steps" (array of {"skill_id": string, "params": object, '
            '"description": string}) and "confidence" (0.0-1.0). '
            "Only use registered skill IDs. Do not include direct motor commands."
        )
        if self._agent_id:
            skills_str = (
                ", ".join(self._agent_skill_names) if self._agent_skill_names else ""
            )
            system_prompt += (
                f"\n\nYou are operating as agent '{self._agent_id}'"
                + (f" with skills: {skills_str}." if skills_str else ".")
            )
        user_content = json.dumps({
            "mission_id": mission.mission_id,
            "robot_id": mission.robot_id,
            "objective": mission.objective,
            "constraints": mission.constraints,
        })
        return {
            "model": "qwenpaw",
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content},
            ],
            "temperature": 0.3,
        }

    def _parse_response(
        self, mission: MissionContext, response_data: dict[str, Any]
    ) -> PlanProposal:
        """Parse the QwenPaw API response into a PlanProposal."""
        plan_id = _new_id("plan")
        now = _now_iso()

        # The response is expected to be a chat-completions response with
        # choices[0].message.content containing the plan JSON.
        try:
            choices = response_data.get("choices", [])
            if not choices:
                return PlanProposal(
                    plan_id=plan_id,
                    mission_id=mission.mission_id,
                    trace_id=mission.trace_id,
                    robot_id=mission.robot_id,
                    is_trusted=False,
                    error="QwenPaw returned no choices",
                    generated_at=now,
                )

            content = choices[0].get("message", {}).get("content", "")
            plan_data = json.loads(content) if isinstance(content, str) else content
            if not isinstance(plan_data, dict):
                return PlanProposal(
                    plan_id=plan_id,
                    mission_id=mission.mission_id,
                    trace_id=mission.trace_id,
                    robot_id=mission.robot_id,
                    is_trusted=False,
                    error="QwenPaw response content is not a JSON object",
                    generated_at=now,
                )

            raw_steps = plan_data.get("steps", [])
            steps: list[PlanStep] = []
            for i, raw_step in enumerate(raw_steps):
                if not isinstance(raw_step, dict):
                    continue
                steps.append(
                    PlanStep(
                        step_id=f"{plan_id}_step_{i}",
                        skill_id=str(raw_step.get("skill_id", "")),
                        params=raw_step.get("params", {}) if isinstance(
                            raw_step.get("params"), dict
                        ) else {},
                        description=str(raw_step.get("description", "")),
                    )
                )

            confidence = float(plan_data.get("confidence", 0.0))
            # Clamp confidence to [0.0, 1.0].
            confidence = max(0.0, min(1.0, confidence))

            return PlanProposal(
                plan_id=plan_id,
                mission_id=mission.mission_id,
                trace_id=mission.trace_id,
                robot_id=mission.robot_id,
                steps=steps,
                confidence=confidence,
                rationale=str(plan_data.get("rationale", "")),
                is_trusted=False,
                generated_at=now,
            )
        except (json.JSONDecodeError, TypeError, ValueError) as exc:
            return PlanProposal(
                plan_id=plan_id,
                mission_id=mission.mission_id,
                trace_id=mission.trace_id,
                robot_id=mission.robot_id,
                is_trusted=False,
                error=f"Failed to parse QwenPaw response: {exc}",
                generated_at=now,
            )
